// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Data;

namespace WebApplication3.Migrations
{
    [DbContext(typeof(KullaniciContext))]
    [Migration("20191224113841_Account")]
    partial class Account
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication3.Models.Kullanici", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UlkeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UlkeId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("WebApplication3.Models.Ulke", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ulkeismi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("Ulke");
                });

            modelBuilder.Entity("WebApplication3.Models.Urun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UlkeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UlkeId");

                    b.ToTable("Urun");
                });

            modelBuilder.Entity("WebApplication3.Models.Kullanici", b =>
                {
                    b.HasOne("WebApplication3.Models.Ulke", null)
                        .WithMany("Kullanici1")
                        .HasForeignKey("UlkeId");
                });

            modelBuilder.Entity("WebApplication3.Models.Ulke", b =>
                {
                    b.HasOne("WebApplication3.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.HasOne("WebApplication3.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId");
                });

            modelBuilder.Entity("WebApplication3.Models.Urun", b =>
                {
                    b.HasOne("WebApplication3.Models.Ulke", null)
                        .WithMany("Urun1")
                        .HasForeignKey("UlkeId");
                });
#pragma warning restore 612, 618
        }
    }
}
